var annotated_dup =
[
    [ "Cartridge", "class_cartridge.html", "class_cartridge" ],
    [ "CartridgeFactory", "class_cartridge_factory.html", null ],
    [ "ChrBankNotSupportedException", "class_chr_bank_not_supported_exception.html", "class_chr_bank_not_supported_exception" ],
    [ "chrRomPage", "structchr_rom_page.html", "structchr_rom_page" ],
    [ "Config", "class_config.html", "class_config" ],
    [ "Controller", "class_controller.html", "class_controller" ],
    [ "cpu", "classcpu.html", "classcpu" ],
    [ "iNes", "classi_nes.html", "classi_nes" ],
    [ "InvalidOpcodeException", "class_invalid_opcode_exception.html", "class_invalid_opcode_exception" ],
    [ "InvalidRomException", "class_invalid_rom_exception.html", "class_invalid_rom_exception" ],
    [ "keyEntry", "structkey_entry.html", "structkey_entry" ],
    [ "Mapper0", "class_mapper0.html", "class_mapper0" ],
    [ "Mapper1", "class_mapper1.html", "class_mapper1" ],
    [ "Mapper2", "class_mapper2.html", "class_mapper2" ],
    [ "Mapper3", "class_mapper3.html", "class_mapper3" ],
    [ "Mapper4", "class_mapper4.html", "class_mapper4" ],
    [ "Mapper66", "class_mapper66.html", "class_mapper66" ],
    [ "Mapper7", "class_mapper7.html", "class_mapper7" ],
    [ "Mapper9", "class_mapper9.html", "class_mapper9" ],
    [ "MapperNotSupportedException", "class_mapper_not_supported_exception.html", "class_mapper_not_supported_exception" ],
    [ "nesHeader", "structnes_header.html", "structnes_header" ],
    [ "opcode_entry", "structopcode__entry.html", "structopcode__entry" ],
    [ "palette_entry", "structpalette__entry.html", "structpalette__entry" ],
    [ "ppu", "classppu.html", "classppu" ],
    [ "PrgBankNotSupportedException", "class_prg_bank_not_supported_exception.html", "class_prg_bank_not_supported_exception" ],
    [ "prgRomPage", "structprg_rom_page.html", "structprg_rom_page" ],
    [ "Renderer", "class_renderer.html", "class_renderer" ],
    [ "RendererFactory", "class_renderer_factory.html", null ],
    [ "RendererNotSupportedException", "class_renderer_not_supported_exception.html", "class_renderer_not_supported_exception" ],
    [ "SDLInitException", "class_s_d_l_init_exception.html", "class_s_d_l_init_exception" ],
    [ "SDLRenderer", "class_s_d_l_renderer.html", "class_s_d_l_renderer" ],
    [ "SDLVideoException", "class_s_d_l_video_exception.html", "class_s_d_l_video_exception" ],
    [ "Yane", "class_yane.html", "class_yane" ],
    [ "YaneException", "class_yane_exception.html", "class_yane_exception" ]
];